const products = [
  {
    id: "p-001",
    productName: "Wireless Headphones",
    category: "Electronics",
    price: 89,
    rating: 4.6,
    stock: 56,
  },
  {
    id: "p-002",
    productName: "Classic Leather Wallet",
    category: "Accessories",
    price: 35,
    rating: 4.4,
    stock: 120,
  },
  {
    id: "p-003",
    productName: "Cotton Crewneck T-Shirt",
    category: "Clothing",
    price: 22,
    rating: 4.2,
    stock: 200,
  },
  {
    id: "p-004",
    productName: "Smart Fitness Watch",
    category: "Electronics",
    price: 129,
    rating: 4.7,
    stock: 45,
  },
  {
    id: "p-005",
    productName: "Stainless Steel Water Bottle",
    category: "Outdoors",
    price: 25,
    rating: 4.5,
    stock: 140,
  },
  {
    id: "p-006",
    productName: "Yoga Mat Pro",
    category: "Fitness",
    price: 39,
    rating: 4.8,
    stock: 80,
  },
  {
    id: "p-007",
    productName: "Minimalist Desk Lamp",
    category: "Home Decor",
    price: 49,
    rating: 4.3,
    stock: 70,
  },
  {
    id: "p-008",
    productName: "Bluetooth Speaker",
    category: "Electronics",
    price: 59,
    rating: 4.5,
    stock: 95,
  },
  {
    id: "p-009",
    productName: "Organic Cotton Hoodie",
    category: "Clothing",
    price: 55,
    rating: 4.4,
    stock: 110,
  },
  {
    id: "p-010",
    productName: "Modern Ceramic Vase",
    category: "Home Decor",
    price: 32,
    rating: 4.2,
    stock: 150,
  },
  {
    id: "p-011",
    productName: "Noise Cancelling Earbuds",
    category: "Electronics",
    price: 99,
    rating: 4.7,
    stock: 66,
  },
  {
    id: "p-012",
    productName: "Adjustable Dumbbell Set",
    category: "Fitness",
    price: 179,
    rating: 4.8,
    stock: 32,
  },
  {
    id: "p-013",
    productName: "Stainless Steel Cookware Set",
    category: "Kitchen",
    price: 199,
    rating: 4.6,
    stock: 40,
  },
  {
    id: "p-014",
    productName: "Soft Throw Blanket",
    category: "Home Decor",
    price: 29,
    rating: 4.5,
    stock: 130,
  },
  {
    id: "p-015",
    productName: "Ergonomic Office Chair",
    category: "Furniture",
    price: 249,
    rating: 4.6,
    stock: 25,
  },
  {
    id: "p-016",
    productName: "LED Gaming Keyboard",
    category: "Electronics",
    price: 69,
    rating: 4.3,
    stock: 90,
  },
  {
    id: "p-017",
    productName: "Mountain Hiking Backpack",
    category: "Outdoors",
    price: 120,
    rating: 4.7,
    stock: 55,
  },
  {
    id: "p-018",
    productName: "Ceramic Coffee Mug",
    category: "Kitchen",
    price: 15,
    rating: 4.1,
    stock: 200,
  },
  {
    id: "p-019",
    productName: "Running Shoes",
    category: "Clothing",
    price: 80,
    rating: 4.5,
    stock: 75,
  },
  {
    id: "p-020",
    productName: "Wooden Cutting Board",
    category: "Kitchen",
    price: 27,
    rating: 4.4,
    stock: 115,
  },
  {
    id: "p-021",
    productName: "Laptop Stand",
    category: "Accessories",
    price: 38,
    rating: 4.6,
    stock: 85,
  },
  {
    id: "p-022",
    productName: "Scented Candle Set",
    category: "Home Decor",
    price: 26,
    rating: 4.3,
    stock: 150,
  },
  {
    id: "p-023",
    productName: "Leather Belt",
    category: "Accessories",
    price: 30,
    rating: 4.4,
    stock: 100,
  },
  {
    id: "p-024",
    productName: "Portable Power Bank",
    category: "Electronics",
    price: 49,
    rating: 4.5,
    stock: 95,
  },
  {
    id: "p-025",
    productName: "Stainless Travel Mug",
    category: "Kitchen",
    price: 20,
    rating: 4.2,
    stock: 140,
  },
  {
    id: "p-026",
    productName: "Canvas Tote Bag",
    category: "Accessories",
    price: 25,
    rating: 4.3,
    stock: 120,
  },
  {
    id: "p-027",
    productName: "Wireless Mouse",
    category: "Electronics",
    price: 25,
    rating: 4.4,
    stock: 130,
  },
  {
    id: "p-028",
    productName: "Digital Alarm Clock",
    category: "Home Decor",
    price: 19,
    rating: 4.1,
    stock: 160,
  },
  {
    id: "p-029",
    productName: "Men’s Slim Fit Jeans",
    category: "Clothing",
    price: 65,
    rating: 4.5,
    stock: 80,
  },
  {
    id: "p-030",
    productName: "Foldable Camping Chair",
    category: "Outdoors",
    price: 55,
    rating: 4.4,
    stock: 70,
  },
  {
    id: "p-031",
    productName: "Smart LED Bulb",
    category: "Electronics",
    price: 18,
    rating: 4.3,
    stock: 180,
  },
  {
    id: "p-032",
    productName: "Women’s Handbag",
    category: "Accessories",
    price: 75,
    rating: 4.6,
    stock: 65,
  },
  {
    id: "p-033",
    productName: "Memory Foam Pillow",
    category: "Home Decor",
    price: 45,
    rating: 4.5,
    stock: 95,
  },
  {
    id: "p-034",
    productName: "Ceramic Dinner Plate Set",
    category: "Kitchen",
    price: 60,
    rating: 4.4,
    stock: 50,
  },
  {
    id: "p-035",
    productName: "Bluetooth Headset",
    category: "Electronics",
    price: 55,
    rating: 4.2,
    stock: 120,
  },
  {
    id: "p-036",
    productName: "Cotton Bath Towel",
    category: "Home Decor",
    price: 19,
    rating: 4.1,
    stock: 160,
  },
  {
    id: "p-037",
    productName: "Wireless Charging Pad",
    category: "Electronics",
    price: 29,
    rating: 4.5,
    stock: 90,
  },
  {
    id: "p-038",
    productName: "Adjustable Yoga Strap",
    category: "Fitness",
    price: 15,
    rating: 4.6,
    stock: 100,
  },
  {
    id: "p-039",
    productName: "Bean Bag Chair",
    category: "Furniture",
    price: 110,
    rating: 4.5,
    stock: 40,
  },
  {
    id: "p-040",
    productName: "Electric Kettle",
    category: "Kitchen",
    price: 35,
    rating: 4.4,
    stock: 100,
  },
  {
    id: "p-041",
    productName: "LED Desk Light",
    category: "Home Decor",
    price: 42,
    rating: 4.3,
    stock: 85,
  },
  {
    id: "p-042",
    productName: "Smartphone Tripod",
    category: "Accessories",
    price: 28,
    rating: 4.4,
    stock: 100,
  },
  {
    id: "p-043",
    productName: "Men’s Casual Shirt",
    category: "Clothing",
    price: 45,
    rating: 4.5,
    stock: 95,
  },
  {
    id: "p-044",
    productName: "Resistance Bands",
    category: "Fitness",
    price: 25,
    rating: 4.6,
    stock: 80,
  },
  {
    id: "p-045",
    productName: "Smart Home Hub",
    category: "Electronics",
    price: 149,
    rating: 4.7,
    stock: 50,
  },
  {
    id: "p-046",
    productName: "Kitchen Knife Set",
    category: "Kitchen",
    price: 99,
    rating: 4.6,
    stock: 55,
  },
  {
    id: "p-047",
    productName: "Women’s Denim Jacket",
    category: "Clothing",
    price: 85,
    rating: 4.5,
    stock: 70,
  },
  {
    id: "p-048",
    productName: "Outdoor Hammock",
    category: "Outdoors",
    price: 60,
    rating: 4.5,
    stock: 75,
  },
  {
    id: "p-049",
    productName: "Laptop Backpack",
    category: "Accessories",
    price: 58,
    rating: 4.6,
    stock: 90,
  },
  {
    id: "p-050",
    productName: "Wireless Keyboard",
    category: "Electronics",
    price: 49,
    rating: 4.4,
    stock: 100,
  },
  {
    id: "p-051",
    productName: "Face Serum",
    category: "Beauty",
    price: 30,
    rating: 4.5,
    stock: 110,
  },
  {
    id: "p-052",
    productName: "Sports Water Bottle",
    category: "Fitness",
    price: 22,
    rating: 4.6,
    stock: 130,
  },
  {
    id: "p-053",
    productName: "LED Strip Lights",
    category: "Electronics",
    price: 39,
    rating: 4.4,
    stock: 100,
  },
  {
    id: "p-054",
    productName: "Wireless Router",
    category: "Electronics",
    price: 89,
    rating: 4.5,
    stock: 60,
  },
  {
    id: "p-055",
    productName: "Women’s Leggings",
    category: "Clothing",
    price: 35,
    rating: 4.6,
    stock: 120,
  },
  {
    id: "p-056",
    productName: "Travel Duffel Bag",
    category: "Accessories",
    price: 70,
    rating: 4.5,
    stock: 90,
  },
  {
    id: "p-057",
    productName: "Ceramic Plant Pot",
    category: "Home Decor",
    price: 25,
    rating: 4.3,
    stock: 100,
  },
  {
    id: "p-058",
    productName: "Electric Toothbrush",
    category: "Beauty",
    price: 59,
    rating: 4.7,
    stock: 80,
  },
  {
    id: "p-059",
    productName: "Smart Doorbell",
    category: "Electronics",
    price: 149,
    rating: 4.8,
    stock: 45,
  },
  {
    id: "p-060",
    productName: "Running Shorts",
    category: "Clothing",
    price: 29,
    rating: 4.4,
    stock: 110,
  },
  {
    id: "p-061",
    productName: "Glass Food Containers",
    category: "Kitchen",
    price: 48,
    rating: 4.5,
    stock: 70,
  },
  {
    id: "p-062",
    productName: "Foam Roller",
    category: "Fitness",
    price: 32,
    rating: 4.6,
    stock: 85,
  },
  {
    id: "p-063",
    productName: "Wireless Car Charger",
    category: "Electronics",
    price: 45,
    rating: 4.5,
    stock: 100,
  },
  {
    id: "p-064",
    productName: "Stylish Wall Clock",
    category: "Home Decor",
    price: 50,
    rating: 4.4,
    stock: 75,
  },
  {
    id: "p-065",
    productName: "Pet Bed",
    category: "Pets",
    price: 60,
    rating: 4.5,
    stock: 80,
  },
  {
    id: "p-066",
    productName: "Gaming Mouse Pad",
    category: "Electronics",
    price: 25,
    rating: 4.6,
    stock: 120,
  },
  {
    id: "p-067",
    productName: "Women’s Sunglasses",
    category: "Accessories",
    price: 55,
    rating: 4.5,
    stock: 100,
  },
  {
    id: "p-068",
    productName: "Wireless Earphones",
    category: "Electronics",
    price: 79,
    rating: 4.4,
    stock: 90,
  },
  {
    id: "p-069",
    productName: "Desk Organizer",
    category: "Home Decor",
    price: 30,
    rating: 4.3,
    stock: 110,
  },
  {
    id: "p-070",
    productName: "Men’s Leather Boots",
    category: "Clothing",
    price: 120,
    rating: 4.6,
    stock: 55,
  },
  {
    id: "p-071",
    productName: "Hair Dryer",
    category: "Beauty",
    price: 65,
    rating: 4.5,
    stock: 95,
  },
  {
    id: "p-072",
    productName: "Portable Cooler",
    category: "Outdoors",
    price: 85,
    rating: 4.4,
    stock: 60,
  },
  {
    id: "p-073",
    productName: "Wooden Bookshelf",
    category: "Furniture",
    price: 220,
    rating: 4.6,
    stock: 30,
  },
  {
    id: "p-074",
    productName: "Silicone Baking Mat",
    category: "Kitchen",
    price: 18,
    rating: 4.3,
    stock: 100,
  },
  {
    id: "p-075",
    productName: "Gaming Headset",
    category: "Electronics",
    price: 99,
    rating: 4.6,
    stock: 65,
  },
  {
    id: "p-076",
    productName: "Aromatherapy Diffuser",
    category: "Home Decor",
    price: 42,
    rating: 4.5,
    stock: 90,
  },
  {
    id: "p-077",
    productName: "Portable Projector",
    category: "Electronics",
    price: 199,
    rating: 4.6,
    stock: 40,
  },
  {
    id: "p-078",
    productName: "Cookbook: Vegan Delights",
    category: "Books",
    price: 35,
    rating: 4.7,
    stock: 80,
  },
  {
    id: "p-079",
    productName: "Weighted Blanket",
    category: "Home Decor",
    price: 90,
    rating: 4.5,
    stock: 60,
  },
  {
    id: "p-080",
    productName: "Electric Screwdriver",
    category: "Tools",
    price: 55,
    rating: 4.6,
    stock: 70,
  },
  {
    id: "p-081",
    productName: "Stainless Steel Watch",
    category: "Accessories",
    price: 140,
    rating: 4.6,
    stock: 45,
  },
  {
    id: "p-082",
    productName: "Running Jacket",
    category: "Clothing",
    price: 75,
    rating: 4.5,
    stock: 85,
  },
  {
    id: "p-083",
    productName: "Wireless Home Camera",
    category: "Electronics",
    price: 89,
    rating: 4.6,
    stock: 65,
  },
  {
    id: "p-084",
    productName: "Sofa Throw Pillow",
    category: "Home Decor",
    price: 25,
    rating: 4.3,
    stock: 100,
  },
  {
    id: "p-085",
    productName: "Cooking Utensil Set",
    category: "Kitchen",
    price: 45,
    rating: 4.5,
    stock: 75,
  },
  {
    id: "p-086",
    productName: "Camping Lantern",
    category: "Outdoors",
    price: 39,
    rating: 4.4,
    stock: 90,
  },
  {
    id: "p-087",
    productName: "Face Moisturizer",
    category: "Beauty",
    price: 28,
    rating: 4.5,
    stock: 110,
  },
  {
    id: "p-088",
    productName: "Adjustable Laptop Table",
    category: "Furniture",
    price: 95,
    rating: 4.5,
    stock: 55,
  },
  {
    id: "p-089",
    productName: "Travel Pillow",
    category: "Accessories",
    price: 22,
    rating: 4.3,
    stock: 120,
  },
  {
    id: "p-090",
    productName: "Men’s Graphic Tee",
    category: "Clothing",
    price: 28,
    rating: 4.4,
    stock: 140,
  },
  {
    id: "p-091",
    productName: "Smart Light Strip",
    category: "Electronics",
    price: 45,
    rating: 4.5,
    stock: 95,
  },
  {
    id: "p-092",
    productName: "Children’s Story Book",
    category: "Books",
    price: 20,
    rating: 4.7,
    stock: 100,
  },
  {
    id: "p-093",
    productName: "Body Lotion",
    category: "Beauty",
    price: 18,
    rating: 4.4,
    stock: 140,
  },
  {
    id: "p-094",
    productName: "Office Desk Organizer",
    category: "Home Decor",
    price: 35,
    rating: 4.4,
    stock: 85,
  },
  {
    id: "p-095",
    productName: "Portable Blender",
    category: "Kitchen",
    price: 59,
    rating: 4.6,
    stock: 70,
  },
  {
    id: "p-096",
    productName: "Smartwatch Charger",
    category: "Electronics",
    price: 25,
    rating: 4.5,
    stock: 90,
  },
  {
    id: "p-097",
    productName: "Travel Makeup Bag",
    category: "Accessories",
    price: 30,
    rating: 4.5,
    stock: 100,
  },
  {
    id: "p-098",
    productName: "Kids’ Toy Car",
    category: "Toys",
    price: 40,
    rating: 4.4,
    stock: 90,
  },
  {
    id: "p-099",
    productName: "Noise Cancelling Headphones",
    category: "Electronics",
    price: 199,
    rating: 4.7,
    stock: 50,
  },
  {
    id: "p-100",
    productName: "Leather Journal",
    category: "Books",
    price: 32,
    rating: 4.6,
    stock: 120,
  },
];

// TODO : Filter => Electronics
// TODO : Sort by => Rating
// TODO : Slice => first 3 (top 3)
// TODO : Map => transform object shape to {name : "Name"}

const filterdProduct = products
  .filter((prd) => prd.category === "Clothing")
  .sort((a, b) => a.rating - b.rating)
  .slice(0, 3)
  .map((prd) => {
    return {name: prd.productName}
  });

console.log(filterdProduct);
